### PR TITLE
Do not encode 0 as null

### PR DESCRIPTION
**Pull request by arnaudgeiser**
I'm not 100% sure what the issue is as I didn't go down the rabbit hole.
However, according to the tests I found on FDB Record Layer codebase, the ordinal 0 for an enum is an invalid value.
Most of their tests are written using `proto2` which didn't enforce an enum to start with a 0 index.

There are some hints on those where the enum is starting with 0 (in particular the first one which tests indices):
- https://github.com/FoundationDB/fdb-record-layer/blob/fbd60ce6c3189c06fb891fd957d37f3fc07c0b9b/fdb-record-layer-core/src/main/proto/index_build.proto#L31
- https://github.com/FoundationDB/fdb-record-layer/blob/036443fe91fe822422fe0d732bfade3c91d68441/fdb-record-layer-core/src/main/proto/record_metadata_options.proto#L39
- https://github.com/FoundationDB/fdb-record-layer/blob/b75305a69eefcc33f934d12dd299197c832273b0/fdb-record-layer-core/src/main/proto/record_cursor.proto#L90

Since I considered 0 being an invalid value, everything makes sense:

```

fdb> getrange \x00 \xff 1000

Range limited to 1000 keys
`\x15\x12\x15!' is `\x02testing14485\x00'
`\x15!\x02demostore\x00\x14' is `\x08\x07\x10\x07(\xb1\xd0\xfa\xcc\x890'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x01\x14' is `\x0a\x10\x08\x01\x12\x02a1\x1a\x06active \x03'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x02\x14' is `\x0a\x13\x08\x02\x12\x02a2\x1a\x09suspended \x01'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x03\x14' is `\x0a\x13\x08\x03\x12\x02a3\x1a\x09suspended \x03'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x04\x14' is `\x0a\x14\x08\x04\x12\x02a4\x1a\x0aterminated \x02'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x05\x14' is `\x0a\x12\x08\x05\x12\x02a5\x1a\x0aterminated'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x06\x14' is `\x0a\x12\x08\x06\x12\x02a6\x1a\x0aterminated'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x01\x15\x01\x14' is `\x12\x1a\x08\x01\x10\x01\x1a\x04a1u1"\x0ea1u1@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x01\x15\x02\x14' is `\x12\x1a\x08\x01\x10\x02\x1a\x04a1u2"\x0ea1u2@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x02\x15\x03\x14' is `\x12\x1a\x08\x02\x10\x03\x1a\x04a2u3"\x0ea2u3@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x04\x14' is `\x12\x1a\x08\x03\x10\x04\x1a\x04a3u4"\x0ea3u5@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x05\x14' is `\x12\x1a\x08\x03\x10\x05\x1a\x04a3u5"\x0ea3u5@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x06\x14' is `\x12\x1a\x08\x03\x10\x06\x1a\x04a3u6"\x0ea3u6@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x01\x15\x01\x14' is `\x1a\x16\x08\x01\x10\x01 \x0a*\x06\x0a\x02p1\x10\x02*\x06\x0a\x02p2\x10\x04'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x01\x15\x02\x14' is `\x1a\x0e\x08\x01\x10\x02 \x1e*\x06\x0a\x02p1\x10\x08'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x03\x15\x03\x14' is `\x1a\x0e\x08\x03\x10\x03 P*\x06\x0a\x02p4\x10\x01'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x04\x15\x04\x14' is `\x1a\x16\x08\x04\x10\x04 \x0a*\x06\x0a\x02p1\x10\x02*\x06\x0a\x02p2\x10\x04'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x04\x15\x05\x14' is `\x1a\x0e\x08\x04\x10\x05 P*\x06\x0a\x02p4\x10\x01'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x01' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x03' is `\x02\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02active\x00\x15\x01\x15\x01' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02suspended\x00\x15\x01\x15\x02' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02suspended\x00\x15\x01\x15\x03' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x04' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x05' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x06' is `'
`\x15!\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x01' is `(\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x03' is `P\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x04' is `Z\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x01' is `\x02\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x03' is `\x03\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a1u1\x00\x15\x02\x15\x01\x15\x01' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a1u2\x00\x15\x02\x15\x01\x15\x02' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a2u3\x00\x15\x02\x15\x02\x15\x03' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a3u4\x00\x15\x02\x15\x03\x15\x04' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a3u5\x00\x15\x02\x15\x03\x15\x05' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a3u6\x00\x15\x02\x15\x03\x15\x06' is `'
`\xfe\x01\xfe\x00\x01hca\x00\x14\x14' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\xfe\x01\xfe\x00\x01hca\x00\x15\x01\x15!' is `\x02testing14485\x00'
`\xfe\x01\xfe\x00\x14\x02testing14485\x00' is `\x15!'
```

There are only 3 rows instead of 4 (the last one should have been represented the `INVALID` 0 value) 

```
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x01' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x03' is `\x02\x00\x00\x00\x00\x00\x00\x00'
```

This PR just adds some tests around it plus a little bit of documentation.

### CODE REVIEW

**Comment by pyr** [comment]
Is it possible this could be tied to the shortcomings pointed to here: https://forums.foundationdb.org/t/querying-an-enum-value/1698?

**Comment by pyr** [comment]
I dug briefly, and `group-by` only supports to different key expressions in the schema plain `KeyExpression` and `NestedKeyExpression`. It is possible a different schema key expression needs to be supported by `group-by`.  https://github.com/exoscale/vinyl/blob/master/src/exoscale/vinyl/schema.clj#L28-L34

We will probably need to explore the built schema to understand what it looks like or should look like.

**Comment by arnaudgeiser** [comment]
Thank you for having a look at this.
I was digging around `KeyExpression` (`schema.clj`) but I didn't find what would be the issue for now.

> Is it possible this could be tied to the shortcomings pointed to here: https://forums.foundationdb.org/t/querying-an-enum-value/1698?

Maybe, thank you for the pointer.

**Comment by pyr** [comment]
> > Is it possible this could be tied to the shortcomings pointed to here: https://forums.foundationdb.org/t/querying-an-enum-value/1698?
> 
> Maybe, thank you for the pointer.

Looking into it more, this seems tied to queries, not index expressions, so unlikely to be exactly that (there could still be a relation).

I think we should explore the indexed rows to understand what data ends up in there, on a hunch it feels as though we're not indexing the enum's ordinal at all, and you get the count for the first entry because the first ordinal is 0 which may be elided in the index.

**Comment by arnaudgeiser** [comment]
> I think we should explore the indexed rows to understand what data ends up in there, on a hunch it feels as though we're not indexing the enum's ordinal at all, and you get the count for the first entry because the first ordinal is 0 which may be elided in the index.

Actually, quite the opposite, I got the count of the last row, which is `2` (Payment.WIRED).

**Comment by arnaudgeiser** [comment]
The issue is not at query time, but the way the index is built.

```
fdb> getrange \x00 \xFF 1000

Range limited to 1000 keys
`\x15\x18\x02demostore\x00\x14' is `\x08\x07\x10\x07(\x8c\x80\xfb\xc2\x890'
`\x15\x18\x02demostore\x00\x15\x01\x15\x01\x15\x01\x14' is `\x0a\x10\x08\x01\x12\x02a1\x1a\x06active \x02'
`\x15\x18\x02demostore\x00\x15\x01\x15\x01\x15\x02\x14' is `\x0a\x11\x08\x02\x12\x02a2\x1a\x09suspended'
`\x15\x18\x02demostore\x00\x15\x01\x15\x01\x15\x03\x14' is `\x0a\x13\x08\x03\x12\x02a3\x1a\x09suspended \x02'
`\x15\x18\x02demostore\x00\x15\x01\x15\x01\x15\x04\x14' is `\x0a\x12\x08\x04\x12\x02a4\x1a\x0aterminated'
`\x15\x18\x02demostore\x00\x15\x01\x15\x02\x15\x01\x15\x01\x14' is `\x12\x1a\x08\x01\x10\x01\x1a\x04a1u1"\x0ea1u1@hello.com'
`\x15\x18\x02demostore\x00\x15\x01\x15\x02\x15\x01\x15\x02\x14' is `\x12\x1a\x08\x01\x10\x02\x1a\x04a1u2"\x0ea1u2@hello.com'
`\x15\x18\x02demostore\x00\x15\x01\x15\x02\x15\x02\x15\x03\x14' is `\x12\x1a\x08\x02\x10\x03\x1a\x04a2u3"\x0ea2u3@hello.com'
`\x15\x18\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x04\x14' is `\x12\x1a\x08\x03\x10\x04\x1a\x04a3u4"\x0ea3u5@hello.com'
`\x15\x18\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x05\x14' is `\x12\x1a\x08\x03\x10\x05\x1a\x04a3u5"\x0ea3u5@hello.com'
`\x15\x18\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x06\x14' is `\x12\x1a\x08\x03\x10\x06\x1a\x04a3u6"\x0ea3u6@hello.com'
`\x15\x18\x02demostore\x00\x15\x01\x15\x03\x15\x01\x15\x01\x14' is `\x1a\x16\x08\x01\x10\x01 \x0a*\x06\x0a\x02p1\x10\x02*\x06\x0a\x02p2\x10\x04'
`\x15\x18\x02demostore\x00\x15\x01\x15\x03\x15\x01\x15\x02\x14' is `\x1a\x0e\x08\x01\x10\x02 \x1e*\x06\x0a\x02p1\x10\x08'
`\x15\x18\x02demostore\x00\x15\x01\x15\x03\x15\x03\x15\x03\x14' is `\x1a\x0e\x08\x03\x10\x03 P*\x06\x0a\x02p4\x10\x01'
`\x15\x18\x02demostore\x00\x15\x01\x15\x03\x15\x04\x15\x04\x14' is `\x1a\x16\x08\x04\x10\x04 \x0a*\x06\x0a\x02p1\x10\x02*\x06\x0a\x02p2\x10\x04'
`\x15\x18\x02demostore\x00\x15\x01\x15\x03\x15\x04\x15\x05\x14' is `\x1a\x0e\x08\x04\x10\x05 P*\x06\x0a\x02p4\x10\x01'
`\x15\x18\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x02' is `\x02\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02account_state\x00\x02active\x00\x15\x01\x15\x01' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02account_state\x00\x02suspended\x00\x15\x01\x15\x02' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02account_state\x00\x02suspended\x00\x15\x01\x15\x03' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x04' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x01' is `(\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x03' is `P\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x04' is `Z\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x01' is `\x02\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x03' is `\x03\x00\x00\x00\x00\x00\x00\x00'
`\x15\x18\x02demostore\x00\x15\x02\x02username\x00\x02a1u1\x00\x15\x02\x15\x01\x15\x01' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02username\x00\x02a1u2\x00\x15\x02\x15\x01\x15\x02' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02username\x00\x02a2u3\x00\x15\x02\x15\x02\x15\x03' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02username\x00\x02a3u4\x00\x15\x02\x15\x03\x15\x04' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02username\x00\x02a3u5\x00\x15\x02\x15\x03\x15\x05' is `'
`\x15\x18\x02demostore\x00\x15\x02\x02username\x00\x02a3u6\x00\x15\x02\x15\x03\x15\x06' is `'
```

There is only one line for `account_payment_count` instead of three :

```
`\x15\x18\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x02' is `\x02\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by arnaudgeiser** [comment]
I'm not 100% sure what the issue is as I didn't go down the rabbit hole.
However, according to the tests I found on FDB Record Layer codebase, the ordinal 0 for an enum is an invalid value.
Most of their tests are written using `proto2` which didn't enforce an enum to start with a 0 index.

There are some hints on those where the enum is starting with 0 (in particular the first one which tests indices):
- https://github.com/FoundationDB/fdb-record-layer/blob/fbd60ce6c3189c06fb891fd957d37f3fc07c0b9b/fdb-record-layer-core/src/main/proto/index_build.proto#L31
- https://github.com/FoundationDB/fdb-record-layer/blob/036443fe91fe822422fe0d732bfade3c91d68441/fdb-record-layer-core/src/main/proto/record_metadata_options.proto#L39
- https://github.com/FoundationDB/fdb-record-layer/blob/b75305a69eefcc33f934d12dd299197c832273b0/fdb-record-layer-core/src/main/proto/record_cursor.proto#L90

Since I considered 0 being an invalid value, everything makes sense:

```

fdb> getrange \x00 \xff 1000

Range limited to 1000 keys
`\x15\x12\x15!' is `\x02testing14485\x00'
`\x15!\x02demostore\x00\x14' is `\x08\x07\x10\x07(\xb1\xd0\xfa\xcc\x890'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x01\x14' is `\x0a\x10\x08\x01\x12\x02a1\x1a\x06active \x03'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x02\x14' is `\x0a\x13\x08\x02\x12\x02a2\x1a\x09suspended \x01'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x03\x14' is `\x0a\x13\x08\x03\x12\x02a3\x1a\x09suspended \x03'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x04\x14' is `\x0a\x14\x08\x04\x12\x02a4\x1a\x0aterminated \x02'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x05\x14' is `\x0a\x12\x08\x05\x12\x02a5\x1a\x0aterminated'
`\x15!\x02demostore\x00\x15\x01\x15\x01\x15\x06\x14' is `\x0a\x12\x08\x06\x12\x02a6\x1a\x0aterminated'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x01\x15\x01\x14' is `\x12\x1a\x08\x01\x10\x01\x1a\x04a1u1"\x0ea1u1@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x01\x15\x02\x14' is `\x12\x1a\x08\x01\x10\x02\x1a\x04a1u2"\x0ea1u2@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x02\x15\x03\x14' is `\x12\x1a\x08\x02\x10\x03\x1a\x04a2u3"\x0ea2u3@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x04\x14' is `\x12\x1a\x08\x03\x10\x04\x1a\x04a3u4"\x0ea3u5@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x05\x14' is `\x12\x1a\x08\x03\x10\x05\x1a\x04a3u5"\x0ea3u5@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x02\x15\x03\x15\x06\x14' is `\x12\x1a\x08\x03\x10\x06\x1a\x04a3u6"\x0ea3u6@hello.com'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x01\x15\x01\x14' is `\x1a\x16\x08\x01\x10\x01 \x0a*\x06\x0a\x02p1\x10\x02*\x06\x0a\x02p2\x10\x04'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x01\x15\x02\x14' is `\x1a\x0e\x08\x01\x10\x02 \x1e*\x06\x0a\x02p1\x10\x08'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x03\x15\x03\x14' is `\x1a\x0e\x08\x03\x10\x03 P*\x06\x0a\x02p4\x10\x01'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x04\x15\x04\x14' is `\x1a\x16\x08\x04\x10\x04 \x0a*\x06\x0a\x02p1\x10\x02*\x06\x0a\x02p2\x10\x04'
`\x15!\x02demostore\x00\x15\x01\x15\x03\x15\x04\x15\x05\x14' is `\x1a\x0e\x08\x04\x10\x05 P*\x06\x0a\x02p4\x10\x01'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x01' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x03' is `\x02\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02active\x00\x15\x01\x15\x01' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02suspended\x00\x15\x01\x15\x02' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02suspended\x00\x15\x01\x15\x03' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x04' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x05' is `'
`\x15!\x02demostore\x00\x15\x02\x02account_state\x00\x02terminated\x00\x15\x01\x15\x06' is `'
`\x15!\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x01' is `(\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x03' is `P\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02total_invoiced\x00\x15\x04' is `Z\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x01' is `\x02\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02usercnt\x00\x15\x03' is `\x03\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a1u1\x00\x15\x02\x15\x01\x15\x01' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a1u2\x00\x15\x02\x15\x01\x15\x02' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a2u3\x00\x15\x02\x15\x02\x15\x03' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a3u4\x00\x15\x02\x15\x03\x15\x04' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a3u5\x00\x15\x02\x15\x03\x15\x05' is `'
`\x15!\x02demostore\x00\x15\x02\x02username\x00\x02a3u6\x00\x15\x02\x15\x03\x15\x06' is `'
`\xfe\x01\xfe\x00\x01hca\x00\x14\x14' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\xfe\x01\xfe\x00\x01hca\x00\x15\x01\x15!' is `\x02testing14485\x00'
`\xfe\x01\xfe\x00\x14\x02testing14485\x00' is `\x15!'
```

There are only 3 rows instead of 4 (the last one should have been represented the `INVALID` 0 value) 

```
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x01' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x02' is `\x01\x00\x00\x00\x00\x00\x00\x00'
`\x15!\x02demostore\x00\x15\x02\x02account_payment_count\x00\x15\x03' is `\x02\x00\x00\x00\x00\x00\x00\x00'
```

This PR just adds some tests around it plus a little bit of documentation.

**Comment by arnaudgeiser** [comment]
@pyr : You will have here the complete explanation of our issue: https://forums.foundationdb.org/t/whats-so-special-about-proto3-and-ordinal-0-for-enums/3301

**Comment by arnaudgeiser** [comment]
Here is a fix proposition: https://github.com/exoscale/vinyl/pull/8/commits/0b1aa87fc5899b18de59f4446bea212a769215af

And a pointer about how it's implemented on FDB Record Layer : https://github.com/FoundationDB/fdb-record-layer/blob/main/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/FieldKeyExpression.java#L156-L161

**Comment by pyr** [comment]
Thanks for digging all the way @arnaudgeiser. Since the shortcomings identified are mostly tied to Protobuf3's encoding of ordinal 0 in enums, I suggest we document explicitly the fact that they should be avoided in vinyl and we leave it at that (I don't have a concrete case to point you but this would prevent any nullable from being indexed)

**Review by pyr — APPROVED** [review]

**Comment by arnaudgeiser** [comment]
[CH47714]

**Pull request merged**
