### PR TITLE
switch to tools.project

### PR DESCRIPTION
**Pull request by pyr**
Drop the dependency on leiningen and move to tools.project, this
will allow easier integration for projects which favor git
dependencies.

Minimal formatting so that the github linting and formatting
actions pass. Tests do not run in github actions yet.

## Development UX changes

One of the key departures from **leiningen** in **tools.deps** is to enforce absolutely no conventions. Here are the ways this impacts regular workflows:

### Jacking in from VSCode Calva

The `:test` alias should be selected

### Jacking in from Emacs

A `.dir-locals.el` file has been added to hint at the correct alias. If you would rather want the ability to edit it on the fly, your configuration will need the equivalent of:

```lisp
(setq cider-edit-jack-in-command t)
```

### No automatic prep tasks

In **leiningen**, `lein javac` can be made implicit, while prep tasks have to explicitly be ran in the **tools.deps** world. This means that protobuf java sources need to be built once (the `check`, `test`, and `jar` targets all include this step but if you jack-in from a fresh close you will need to `make build` before jacking in)

### CODE REVIEW

**Review by bcachet — APPROVED** [review]
Validated with Calva (VSCode)
Makefile rules have been validated too

**Comment by arnaudgeiser** [comment]
When trying to evaluate `exoscale.vinyl.store-test`, I end up with the following Exception:

```
Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:440).
exoscale.vinyl.Demostore$Account
```

**Comment by bcachet** [comment]
> When trying to evaluate `exoscale.vinyl.store-test`, I end up with the following Exception:
> 
> ```
> Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:440).
> exoscale.vinyl.Demostore$Account
> ```

I have same issue (even if I run `make build` to ensure pre tasks are run (which may not be needed as Java file generated by `protoc` are already there))

**Comment by arnaudgeiser** [comment]
I forgot the `make build` on my side.
It's working as expected.

**Review by arnaudgeiser — APPROVED** [review]

**Comment by bcachet** [comment]
Running `git clean -df -dx` && `make build` && `running tests` was ok

I am really surprised to see that `store-test` rely on a FDB cluster running, but we have no docker-compose setup locally
I am really surprised also to see that those tests are not run on any CI (being Github Action or Jenkins)

**Pull request merged**
